# Java:
#   image: "java:latest"
# Ruby:
#   image: "ruby:latest"
  php:
    build: ./php
    volumes:
      - .:/root/sdk-integration-tests
    command:
      - /bin/bash
      - /root/sdk-integration-tests/php/bootstrap.sh

  node:
   build: ./node
   volumes:
     - .:/root/sdk-integration-tests
   command:
     - /bin/bash
     - /root/sdk-integration-tests/node/bootstrap.sh

  ruby:
    build: ./ruby
    volumes:
      - .:/root/sdk-integration-tests
    command:
      - /bin/bash
      - /root/sdk-integration-tests/ruby/bootstrap.sh
  java:
    build: ./java
    volumes:
      - .:/root/sdk-integration-tests
    command:
      - /bin/bash
      - /root/sdk-integration-tests/java/bootstrap.sh
